//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiSCADA_ST.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndiSCADA_ST.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level.
        /// </summary>
        public static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amp Hr PV.
        /// </summary>
        public static string ActualAmpHr {
            get {
                return ResourceManager.GetString("ActualAmpHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Current.
        /// </summary>
        public static string ActualCurrent {
            get {
                return ResourceManager.GetString("ActualCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual pH.
        /// </summary>
        public static string ActualpH {
            get {
                return ResourceManager.GetString("ActualpH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Voltage.
        /// </summary>
        public static string ActualVoltage {
            get {
                return ResourceManager.GetString("ActualVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Weight.
        /// </summary>
        public static string ActualWeight {
            get {
                return ResourceManager.GetString("ActualWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Formula.
        /// </summary>
        public static string AddEditFormula {
            get {
                return ResourceManager.GetString("AddEditFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Parameter.
        /// </summary>
        public static string AddNewParameter {
            get {
                return ResourceManager.GetString("AddNewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Part Details.
        /// </summary>
        public static string AddNewPartDetails {
            get {
                return ResourceManager.GetString("AddNewPartDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddNewUserTitle {
            get {
                return ResourceManager.GetString("AddNewUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Part.
        /// </summary>
        public static string AddPart {
            get {
                return ResourceManager.GetString("AddPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm And Event.
        /// </summary>
        public static string AlarmAndEvent {
            get {
                return ResourceManager.GetString("AlarmAndEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Condition.
        /// </summary>
        public static string AlarmCondition {
            get {
                return ResourceManager.GetString("AlarmCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Count.
        /// </summary>
        public static string AlarmCount {
            get {
                return ResourceManager.GetString("AlarmCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlarmDateTime.
        /// </summary>
        public static string AlarmDateTime {
            get {
                return ResourceManager.GetString("AlarmDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm and Event History.
        /// </summary>
        public static string AlarmEventHistory {
            get {
                return ResourceManager.GetString("AlarmEventHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Group.
        /// </summary>
        public static string AlarmGroup {
            get {
                return ResourceManager.GetString("AlarmGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Name.
        /// </summary>
        public static string AlarmName {
            get {
                return ResourceManager.GetString("AlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm On.
        /// </summary>
        public static string AlarmOn {
            get {
                return ResourceManager.GetString("AlarmOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Status.
        /// </summary>
        public static string AlarmStatus {
            get {
                return ResourceManager.GetString("AlarmStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Alarm Summary : .
        /// </summary>
        public static string AlarmSummary {
            get {
                return ResourceManager.GetString("AlarmSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Text.
        /// </summary>
        public static string AlarmText {
            get {
                return ResourceManager.GetString("AlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Time.
        /// </summary>
        public static string AlarmTime {
            get {
                return ResourceManager.GetString("AlarmTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Time And Top Drip.
        /// </summary>
        public static string AlarmTimeAndTopDrip {
            get {
                return ResourceManager.GetString("AlarmTimeAndTopDrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Type.
        /// </summary>
        public static string AlarmType {
            get {
                return ResourceManager.GetString("AlarmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amp Hr.
        /// </summary>
        public static string AmpHr {
            get {
                return ResourceManager.GetString("AmpHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Current.
        /// </summary>
        public static string AppliedCurrent {
            get {
                return ResourceManager.GetString("AppliedCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto / Manual.
        /// </summary>
        public static string AutoManual {
            get {
                return ResourceManager.GetString("AutoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto / Manual Status.
        /// </summary>
        public static string AutoManualStatus {
            get {
                return ResourceManager.GetString("AutoManualStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg: .
        /// </summary>
        public static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrel/Basket Basics :.
        /// </summary>
        public static string BarrelBasketBasics {
            get {
                return ResourceManager.GetString("BarrelBasketBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrel Motor.
        /// </summary>
        public static string BarrelMotor {
            get {
                return ResourceManager.GetString("BarrelMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrel Motor Status.
        /// </summary>
        public static string BarrelMotorStatus {
            get {
                return ResourceManager.GetString("BarrelMotorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Barrel Motor.
        /// </summary>
        public static string BaseBarrelMotor {
            get {
                return ResourceManager.GetString("BaseBarrelMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass ON/OFF.
        /// </summary>
        public static string BypassONOFF {
            get {
                return ResourceManager.GetString("BypassONOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Current.
        /// </summary>
        public static string CalculateCurrent {
            get {
                return ResourceManager.GetString("CalculateCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Formula.
        /// </summary>
        public static string CalculationFormula {
            get {
                return ResourceManager.GetString("CalculationFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Chemical Consumption Summary: .
        /// </summary>
        public static string ChemicalConsumptionSummary {
            get {
                return ResourceManager.GetString("ChemicalConsumptionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Name.
        /// </summary>
        public static string ChemicalName {
            get {
                return ResourceManager.GetString("ChemicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language .
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to close IndiSCADA ?.
        /// </summary>
        public static string closeIndiSCADAWarning {
            get {
                return ResourceManager.GetString("closeIndiSCADAWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Communication Status .
        /// </summary>
        public static string CommunicationStatus {
            get {
                return ResourceManager.GetString("CommunicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Quantity.
        /// </summary>
        public static string ConsumptionQuantity {
            get {
                return ResourceManager.GetString("ConsumptionQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Database.
        /// </summary>
        public static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PartMaster.
        /// </summary>
        public static string CreatePartMaster {
            get {
                return ResourceManager.GetString("CreatePartMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Trolley.
        /// </summary>
        public static string CrossTrolley {
            get {
                return ResourceManager.GetString("CrossTrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Trolley 1.
        /// </summary>
        public static string CrossTrolley1 {
            get {
                return ResourceManager.GetString("CrossTrolley1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Trolley Inputs.
        /// </summary>
        public static string CrossTrolleyInputs {
            get {
                return ResourceManager.GetString("CrossTrolleyInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Trolley OutPut.
        /// </summary>
        public static string CrossTrolleyOutPut {
            get {
                return ResourceManager.GetString("CrossTrolleyOutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative A-Hr.
        /// </summary>
        public static string CumulativeAmpHr {
            get {
                return ResourceManager.GetString("CumulativeAmpHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Current: .
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current PV.
        /// </summary>
        public static string CurrentPV {
            get {
                return ResourceManager.GetString("CurrentPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User: .
        /// </summary>
        public static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleTime.
        /// </summary>
        public static string CycleTime {
            get {
                return ResourceManager.GetString("CycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Generation.
        /// </summary>
        public static string DatabaseGeneration {
            get {
                return ResourceManager.GetString("DatabaseGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data View.
        /// </summary>
        public static string DataView {
            get {
                return ResourceManager.GetString("DataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dehydrator.
        /// </summary>
        public static string Dehydrator {
            get {
                return ResourceManager.GetString("Dehydrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Parameter.
        /// </summary>
        public static string DeleteParameter {
            get {
                return ResourceManager.GetString("DeleteParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Part.
        /// </summary>
        public static string DeletePart {
            get {
                return ResourceManager.GetString("DeletePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosing.
        /// </summary>
        public static string Dosing {
            get {
                return ResourceManager.GetString("Dosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Status :.
        /// </summary>
        public static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download to PLC.
        /// </summary>
        public static string DownloadtoPLC {
            get {
                return ResourceManager.GetString("DownloadtoPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dryer.
        /// </summary>
        public static string Dryer {
            get {
                return ResourceManager.GetString("Dryer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dryer 1.
        /// </summary>
        public static string Dryer1 {
            get {
                return ResourceManager.GetString("Dryer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dryer 2.
        /// </summary>
        public static string Dryer2 {
            get {
                return ResourceManager.GetString("Dryer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dryer 3.
        /// </summary>
        public static string Dryer3 {
            get {
                return ResourceManager.GetString("Dryer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dryer / Cross Trolley.
        /// </summary>
        public static string DryerCrossTrolley {
            get {
                return ResourceManager.GetString("DryerCrossTrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dryer Input.
        /// </summary>
        public static string DryerInput {
            get {
                return ResourceManager.GetString("DryerInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dryer Name.
        /// </summary>
        public static string DryerName {
            get {
                return ResourceManager.GetString("DryerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dryer Output.
        /// </summary>
        public static string DryerOutput {
            get {
                return ResourceManager.GetString("DryerOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Parameter.
        /// </summary>
        public static string EditParameter {
            get {
                return ResourceManager.GetString("EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Part Details.
        /// </summary>
        public static string EditPartDetails {
            get {
                return ResourceManager.GetString("EditPartDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        public static string EmailID {
            get {
                return ResourceManager.GetString("EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Datbase Name :.
        /// </summary>
        public static string EnterDatbaseName {
            get {
                return ResourceManager.GetString("EnterDatbaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Pump Name.
        /// </summary>
        public static string FilterPumpName {
            get {
                return ResourceManager.GetString("FilterPumpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Pump/Oil Skimmer.
        /// </summary>
        public static string FilterPumpOilSkimmer {
            get {
                return ResourceManager.GetString("FilterPumpOilSkimmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Rate.
        /// </summary>
        public static string FlowRate {
            get {
                return ResourceManager.GetString("FlowRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.R./T. Based.
        /// </summary>
        public static string FlowRateTimerBased {
            get {
                return ResourceManager.GetString("FlowRateTimerBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Graph.
        /// </summary>
        public static string GenerateGraph {
            get {
                return ResourceManager.GetString("GenerateGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Data.
        /// </summary>
        public static string GetData {
            get {
                return ResourceManager.GetString("GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPut.
        /// </summary>
        public static string GetPut {
            get {
                return ResourceManager.GetString("GetPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Set Point.
        /// </summary>
        public static string HighSetPoint {
            get {
                return ResourceManager.GetString("HighSetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical.
        /// </summary>
        public static string Historical {
            get {
                return ResourceManager.GetString("Historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndiSCADA Closing...
        /// </summary>
        public static string IndiSCADAClosing {
            get {
                return ResourceManager.GetString("IndiSCADAClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndiSCADA-ST.
        /// </summary>
        public static string IndiSCADAST {
            get {
                return ResourceManager.GetString("IndiSCADAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        public static string Initialize {
            get {
                return ResourceManager.GetString("Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Status.
        /// </summary>
        public static string IOStatus {
            get {
                return ResourceManager.GetString("IOStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Calculation Required.
        /// </summary>
        public static string isCalculationRequired {
            get {
                return ResourceManager.GetString("isCalculationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Download To PLC.
        /// </summary>
        public static string isDownloadToPLC {
            get {
                return ResourceManager.GetString("isDownloadToPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is In Load Data.
        /// </summary>
        public static string isInLoadData {
            get {
                return ResourceManager.GetString("isInLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is In Report.
        /// </summary>
        public static string isInReport {
            get {
                return ResourceManager.GetString("isInReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Primary Key.
        /// </summary>
        public static string isPrimaryKey {
            get {
                return ResourceManager.GetString("isPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Read Only For Next Load.
        /// </summary>
        public static string isReadOnlyForNextLoad {
            get {
                return ResourceManager.GetString("isReadOnlyForNextLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Last: .
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Count.
        /// </summary>
        public static string LoadCount {
            get {
                return ResourceManager.GetString("LoadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader Input.
        /// </summary>
        public static string LoaderInput {
            get {
                return ResourceManager.GetString("LoaderInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader OutPut.
        /// </summary>
        public static string LoaderOutPut {
            get {
                return ResourceManager.GetString("LoaderOutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load No.
        /// </summary>
        public static string LoadNo {
            get {
                return ResourceManager.GetString("LoadNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Number.
        /// </summary>
        public static string LoadNumber {
            get {
                return ResourceManager.GetString("LoadNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Type.
        /// </summary>
        public static string LoadType {
            get {
                return ResourceManager.GetString("LoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginBTN {
            get {
                return ResourceManager.GetString("LoginBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Set Point.
        /// </summary>
        public static string LowSetPoint {
            get {
                return ResourceManager.GetString("LowSetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual/Auto.
        /// </summary>
        public static string ManualAuto {
            get {
                return ResourceManager.GetString("ManualAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Current.
        /// </summary>
        public static string ManualCurrent {
            get {
                return ResourceManager.GetString("ManualCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual On/Off.
        /// </summary>
        public static string ManualOnOff {
            get {
                return ResourceManager.GetString("ManualOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Value.
        /// </summary>
        public static string MaximumValue {
            get {
                return ResourceManager.GetString("MaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Value.
        /// </summary>
        public static string MinimumValue {
            get {
                return ResourceManager.GetString("MinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM DD.
        /// </summary>
        public static string MMDD {
            get {
                return ResourceManager.GetString("MMDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Status.
        /// </summary>
        public static string MotorStatus {
            get {
                return ResourceManager.GetString("MotorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Architecture.
        /// </summary>
        public static string NetworkArchitecture {
            get {
                return ResourceManager.GetString("NetworkArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Load.
        /// </summary>
        public static string NextLoad {
            get {
                return ResourceManager.GetString("NextLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Load Settings.
        /// </summary>
        public static string NextLoadSettings {
            get {
                return ResourceManager.GetString("NextLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Load Update.
        /// </summary>
        public static string NextLoadUpdate {
            get {
                return ResourceManager.GetString("NextLoadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitric Station Selection.
        /// </summary>
        public static string NitricStationSelection {
            get {
                return ResourceManager.GetString("NitricStationSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Shifts.
        /// </summary>
        public static string NumberofShifts {
            get {
                return ResourceManager.GetString("NumberofShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Shifts : Set Shift Timings.
        /// </summary>
        public static string NumberOfShiftsSetShiftTimings {
            get {
                return ResourceManager.GetString("NumberOfShiftsSetShiftTimings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Skimmer Name.
        /// </summary>
        public static string OilSkimmerName {
            get {
                return ResourceManager.GetString("OilSkimmerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON/OFF Status.
        /// </summary>
        public static string ONOFF {
            get {
                return ResourceManager.GetString("ONOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        public static string ParameterName {
            get {
                return ResourceManager.GetString("ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Count.
        /// </summary>
        public static string PartCount {
            get {
                return ResourceManager.GetString("PartCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Master.
        /// </summary>
        public static string PartMaster {
            get {
                return ResourceManager.GetString("PartMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Name.
        /// </summary>
        public static string PartName {
            get {
                return ResourceManager.GetString("PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Qty.
        /// </summary>
        public static string PartQty {
            get {
                return ResourceManager.GetString("PartQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pH.
        /// </summary>
        public static string pH {
            get {
                return ResourceManager.GetString("pH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pH High SP.
        /// </summary>
        public static string pHHighSP {
            get {
                return ResourceManager.GetString("pHHighSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pH Low SP.
        /// </summary>
        public static string pHLowSP {
            get {
                return ResourceManager.GetString("pHLowSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pH PV.
        /// </summary>
        public static string pHPV {
            get {
                return ResourceManager.GetString("pHPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Auto.
        /// </summary>
        public static string PlantAuto {
            get {
                return ResourceManager.GetString("PlantAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Cycle ON.
        /// </summary>
        public static string PlantCycleON {
            get {
                return ResourceManager.GetString("PlantCycleON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Cycle Reset.
        /// </summary>
        public static string PlantCycleReset {
            get {
                return ResourceManager.GetString("PlantCycleReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Cycle Start.
        /// </summary>
        public static string PlantCycleStart {
            get {
                return ResourceManager.GetString("PlantCycleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Emergency Stop.
        /// </summary>
        public static string PlantEmergencyStop {
            get {
                return ResourceManager.GetString("PlantEmergencyStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Status.
        /// </summary>
        public static string PlantStatus {
            get {
                return ResourceManager.GetString("PlantStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant View.
        /// </summary>
        public static string PlantView {
            get {
                return ResourceManager.GetString("PlantView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power ON.
        /// </summary>
        public static string PowerON {
            get {
                return ResourceManager.GetString("PowerON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites.
        /// </summary>
        public static string Prerequisites {
            get {
                return ResourceManager.GetString("Prerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Production Data Summary: .
        /// </summary>
        public static string ProductionDataSummary {
            get {
                return ResourceManager.GetString("ProductionDataSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectifier.
        /// </summary>
        public static string Rectifier {
            get {
                return ResourceManager.GetString("Rectifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Rectifier Current Consumption Summary: .
        /// </summary>
        public static string RectifierCurrentConsumptionSummary {
            get {
                return ResourceManager.GetString("RectifierCurrentConsumptionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectifier Name.
        /// </summary>
        public static string RectifierName {
            get {
                return ResourceManager.GetString("RectifierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectifier Station Name.
        /// </summary>
        public static string RectifierStationName {
            get {
                return ResourceManager.GetString("RectifierStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectifier Total current (Amp/hr).
        /// </summary>
        public static string RectifierTotalcurrent {
            get {
                return ResourceManager.GetString("RectifierTotalcurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemainingT..
        /// </summary>
        public static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Part.
        /// </summary>
        public static string RemovePart {
            get {
                return ResourceManager.GetString("RemovePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Amp Hr.
        /// </summary>
        public static string ResetAmpHr {
            get {
                return ResourceManager.GetString("ResetAmpHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Parameter.
        /// </summary>
        public static string SaveParameter {
            get {
                return ResourceManager.GetString("SaveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Part Details.
        /// </summary>
        public static string SavePartDetails {
            get {
                return ResourceManager.GetString("SavePartDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Name.
        /// </summary>
        public static string ScreenName {
            get {
                return ResourceManager.GetString("ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec.
        /// </summary>
        public static string SecondsUnit {
            get {
                return ResourceManager.GetString("SecondsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Part List.
        /// </summary>
        public static string SelectedPartList {
            get {
                return ResourceManager.GetString("SelectedPartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Part Description :.
        /// </summary>
        public static string SelectPartDescription {
            get {
                return ResourceManager.GetString("SelectPartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Part Number :.
        /// </summary>
        public static string SelectPartNumber {
            get {
                return ResourceManager.GetString("SelectPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sql Server Name :.
        /// </summary>
        public static string SelectSqlServerName {
            get {
                return ResourceManager.GetString("SelectSqlServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set ml (A-h/ml).
        /// </summary>
        public static string Setml {
            get {
                return ResourceManager.GetString("Setml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set pH.
        /// </summary>
        public static string SetpH {
            get {
                return ResourceManager.GetString("SetpH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Time.
        /// </summary>
        public static string SetTime {
            get {
                return ResourceManager.GetString("SetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Weight.
        /// </summary>
        public static string SetWeight {
            get {
                return ResourceManager.GetString("SetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string ShiftEndTime {
            get {
                return ResourceManager.GetString("ShiftEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Hours.
        /// </summary>
        public static string ShiftHours {
            get {
                return ResourceManager.GetString("ShiftHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Number.
        /// </summary>
        public static string ShiftNumber {
            get {
                return ResourceManager.GetString("ShiftNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Settings.
        /// </summary>
        public static string ShiftSettings {
            get {
                return ResourceManager.GetString("ShiftSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string ShiftStartTime {
            get {
                return ResourceManager.GetString("ShiftStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string ShiftStartTimes {
            get {
                return ResourceManager.GetString("ShiftStartTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Parts.
        /// </summary>
        public static string ShowAllParts {
            get {
                return ResourceManager.GetString("ShowAllParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Star Fasteners Pvt. Ltd. .
        /// </summary>
        public static string StarFastenersPvtLtd {
            get {
                return ResourceManager.GetString("StarFastenersPvtLtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Name.
        /// </summary>
        public static string StationName {
            get {
                return ResourceManager.GetString("StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station No.
        /// </summary>
        public static string StationNo {
            get {
                return ResourceManager.GetString("StationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Selection.
        /// </summary>
        public static string StationSelection {
            get {
                return ResourceManager.GetString("StationSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station to be operated.
        /// </summary>
        public static string Stationtobeoperated {
            get {
                return ResourceManager.GetString("Stationtobeoperated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station/Wagon Top Drip.
        /// </summary>
        public static string StationWagonTopDrip {
            get {
                return ResourceManager.GetString("StationWagonTopDrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Inputs.
        /// </summary>
        public static string SystemInputs {
            get {
                return ResourceManager.GetString("SystemInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System OutPuts.
        /// </summary>
        public static string SystemOutPuts {
            get {
                return ResourceManager.GetString("SystemOutPuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System / Unloader / Loader Status.
        /// </summary>
        public static string SystemUnloaderLoaderStatus {
            get {
                return ResourceManager.GetString("SystemUnloaderLoaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name.
        /// </summary>
        public static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag List.
        /// </summary>
        public static string TagList {
            get {
                return ResourceManager.GetString("TagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Details.
        /// </summary>
        public static string TankDetails {
            get {
                return ResourceManager.GetString("TankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Name.
        /// </summary>
        public static string TankName {
            get {
                return ResourceManager.GetString("TankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank / Tray Bypass.
        /// </summary>
        public static string TankTrayBypass {
            get {
                return ResourceManager.GetString("TankTrayBypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature And pH.
        /// </summary>
        public static string TemperatureAndpH {
            get {
                return ResourceManager.GetString("TemperatureAndpH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature High SP.
        /// </summary>
        public static string TemperatureHighSP {
            get {
                return ResourceManager.GetString("TemperatureHighSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Low SP.
        /// </summary>
        public static string TemperatureLowSP {
            get {
                return ResourceManager.GetString("TemperatureLowSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature PV.
        /// </summary>
        public static string TemperaturePV {
            get {
                return ResourceManager.GetString("TemperaturePV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature SV.
        /// </summary>
        public static string TemperatureSV {
            get {
                return ResourceManager.GetString("TemperatureSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Drip.
        /// </summary>
        public static string TopDrip {
            get {
                return ResourceManager.GetString("TopDrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: .
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Name.
        /// </summary>
        public static string TrayName {
            get {
                return ResourceManager.GetString("TrayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string Trends {
            get {
                return ResourceManager.GetString("Trends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Status.
        /// </summary>
        public static string TripStatus {
            get {
                return ResourceManager.GetString("TripStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloader.
        /// </summary>
        public static string Unloader {
            get {
                return ResourceManager.GetString("Unloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloader 1.
        /// </summary>
        public static string Unloader1 {
            get {
                return ResourceManager.GetString("Unloader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloader Input.
        /// </summary>
        public static string UnloaderInput {
            get {
                return ResourceManager.GetString("UnloaderInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloader Output.
        /// </summary>
        public static string UnloaderOutput {
            get {
                return ResourceManager.GetString("UnloaderOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Part.
        /// </summary>
        public static string UpdatePart {
            get {
                return ResourceManager.GetString("UpdatePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Master.
        /// </summary>
        public static string UserMaster {
            get {
                return ResourceManager.GetString("UserMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage PV.
        /// </summary>
        public static string VoltagePV {
            get {
                return ResourceManager.GetString("VoltagePV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon.
        /// </summary>
        public static string Wagon {
            get {
                return ResourceManager.GetString("Wagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon 1.
        /// </summary>
        public static string Wagon1 {
            get {
                return ResourceManager.GetString("Wagon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon1 WCS.
        /// </summary>
        public static string Wagon1WCS {
            get {
                return ResourceManager.GetString("Wagon1WCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon 2.
        /// </summary>
        public static string Wagon2 {
            get {
                return ResourceManager.GetString("Wagon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon2 WCS.
        /// </summary>
        public static string Wagon2WCS {
            get {
                return ResourceManager.GetString("Wagon2WCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon 3.
        /// </summary>
        public static string Wagon3 {
            get {
                return ResourceManager.GetString("Wagon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon3 WCS.
        /// </summary>
        public static string Wagon3WCS {
            get {
                return ResourceManager.GetString("Wagon3WCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon 4.
        /// </summary>
        public static string Wagon4 {
            get {
                return ResourceManager.GetString("Wagon4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon4 WCS.
        /// </summary>
        public static string Wagon4WCS {
            get {
                return ResourceManager.GetString("Wagon4WCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon 5.
        /// </summary>
        public static string Wagon5 {
            get {
                return ResourceManager.GetString("Wagon5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon5 WCS.
        /// </summary>
        public static string Wagon5WCS {
            get {
                return ResourceManager.GetString("Wagon5WCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon 6.
        /// </summary>
        public static string Wagon6 {
            get {
                return ResourceManager.GetString("Wagon6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon6 WCS.
        /// </summary>
        public static string Wagon6WCS {
            get {
                return ResourceManager.GetString("Wagon6WCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon 7.
        /// </summary>
        public static string Wagon7 {
            get {
                return ResourceManager.GetString("Wagon7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon7 WCS.
        /// </summary>
        public static string Wagon7WCS {
            get {
                return ResourceManager.GetString("Wagon7WCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon Barrel.
        /// </summary>
        public static string WagonBarrel {
            get {
                return ResourceManager.GetString("WagonBarrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon Basics :.
        /// </summary>
        public static string WagonBasics {
            get {
                return ResourceManager.GetString("WagonBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon/Dryer/CT Alarm Time.
        /// </summary>
        public static string WagonDryerCTAlarmTime {
            get {
                return ResourceManager.GetString("WagonDryerCTAlarmTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon Inputs.
        /// </summary>
        public static string WagonInputs {
            get {
                return ResourceManager.GetString("WagonInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon LoadString Status.
        /// </summary>
        public static string WagonLoadStringStatus {
            get {
                return ResourceManager.GetString("WagonLoadStringStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon Number.
        /// </summary>
        public static string WagonNumber {
            get {
                return ResourceManager.GetString("WagonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon Outputs.
        /// </summary>
        public static string WagonOutputs {
            get {
                return ResourceManager.GetString("WagonOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon Status.
        /// </summary>
        public static string WagonStatus {
            get {
                return ResourceManager.GetString("WagonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCS.
        /// </summary>
        public static string WCS {
            get {
                return ResourceManager.GetString("WCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
